
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 970389
    url: jdbc:mysql://106.14.7.29:3306/test
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    check-template-location: false
    content-type: text/html
    check-template: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
security:
  user:
    name: zx
    password: 970389
  basic:
    path: ["/**"]
    enabled: false



